### ISSUE TITLE
KeyError: 'upscalers' when opening Krita

### ISSUE THREAD

**Issue by zznewclear13** [Interpause/auto-sd-krita#12]
**Describe the bug**
When I try to run krita, an error occur, saying "KeyError: 'upscalers'".

**To Reproduce**
1. Run `webui.bat`.
2. Open Krita, and an error message appears.

**Expected behavior**
At least I should be able to open krita...

**Screenshots**
![image](https://user-images.githubusercontent.com/57306674/194841937-11acfb4b-7b27-4dbb-9ebb-b3ede43946fc.png)
![image](https://user-images.githubusercontent.com/57306674/194842027-62fa817d-042e-4cf1-abfc-8b3a99eba332.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Krita 5.1.1
 - Commit revision 2d5b3c2842e7c99bed614c562dc6501c53c2fa78

**Additional context**

```
Traceback (most recent call last):
  File "C:\Program Files\Krita (x64)\lib\krita-python-libs\krita\dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "C:\Users\shisan\AppData\Roaming\krita\pykrita\krita_diff\docker.py", line 28, in __init__
    self.update_remote_config()
  File "C:\Users\shisan\AppData\Roaming\krita\pykrita\krita_diff\docker.py", line 91, in update_remote_config
    if script.update_config():
  File "C:\Users\shisan\AppData\Roaming\krita\pykrita\krita_diff\script.py", line 121, in update_config
    assert len(self.opt["upscalers"]) > 0
KeyError: 'upscalers'
```

**Comment by zznewclear13** [comment]
My `self.opt` looks like this.
```
self.opt = {'components': [{'id': 525, 'props': {'elem_id': 'quicksettings', 'style': {}, 'type': 'row', 'visible': True}, 'type': 'row'}, {'id': 526, 'props': {'choices': [r'animefull-final-pruned\model.ckpt [925997e9]', r'animefull-latest\model.ckpt [e6e8e1fc]', r'original\sd-v1-4.ckpt [7460a6fa]'], 'label': 'Stable Diffusion checkpoint', 'name': 'dropdown', 'show_label': True, 'style': {}, 'value': r'animefull-latest\model.ckpt [e6e8e1fc]', 'visible': True}, 'type': 'dropdown'}, {'id': 527, 'props': {'style': {}, 'type': 'form', 'visible': True}, 'type': 'form'}, {'id': 528, 'props': {'style': {}, 'visible': True}, 'type': 'tabs'}, {'id': 529, 'props': {'id': 'txt2img', 'label': 'txt2img', 'style': {}, 'visible': True}, 'type': 'tabitem'}, {'id': 1, 'props': {'elem_id': 'toprow', 'style': {}, 'type': 'row', 'visible': True}, 'type': 'row'}, {'id': 2, 'props': {'min_width': 320, 'scale': 4, 'style': {}, 'type': 'column', 'variant': 'default', 'visible': True}, 'type': 'column'}, {'id': 3, 'props': {'style': {}, 'type': 'row', 'visible': True}, 'type': 'row'}, {'id': 4, 'props': {'min_width': 320, 'scale': 80, 'style': {}, 'type': 'column', 'variant': 'default', 'visible': True}, 'type': 'column'}, {'id': 5, 'props': {'style': {}, 'type': 'row', 'visible': True}, 'type': 'row'}, {'id': 6, 'props': {'elem_id': 'txt2img_prompt', 'label': 'Prompt', 'lines': 2, 'max_lines': 20, 'name': 'textbox', 'placeholder': 'Prompt', 'show_label': False, 'style': {}, 'value': '', 'visible': True}, 'type': 'textbox'}, {'id': 7, 'props': {'style': {}, 'type': 'form', 'visible': True}, 'type': 'form'}, {'id': 8, 'props': {'elem_id': 'roll_col', 'min_width': 320, 'scale': 1, 'style': {}, 'type': 'column', 'variant': 'default', 'visible': True}, 'type': 'column'}, {'id': 9, 'props': {'elem_id': 'roll', 'name': 'button', 'style': {}, 'value': '🎨', 'variant': 'secondary', 'visible': True}, 'type': 'button'}, {'id': 10, 'props': {'elem_id': 'paste', 'name': 'button', 'style': {}, 'value': '↙️', 'variant': 'secondary', 'visible': True}, 'type': 'button'}, {'id': 11, 'props': {'elem_id': 'txt2img_token_counter', 'name': 'html', 'show_label': True, 'style': {}, 'value': '<span></span>', 'visible': True}, 'type': 'html'}, {'id': 12, 'props': {'elem_id': 'txt2img_token_button', 'name': 'button', 'style': {}, 'value': 'Run', 'variant': 'secondary', 'visible': False}, 'type': 'button'}, {'id': 13, 'props': {'elem_id': 'style_pos_col', 'min_width': 320, 'scale': 10, 'style': {}, 'type': 'column', 'variant': 'default', 'visible': True}, 'type': 'column'}, {'id': 14, 'props': {'choices': ['None'], 'elem_id': 'txt2img_style_index', 'label': 'Style 1', 'name': 'dropdown', 'show_label': True, 'style': {}, 'value': 'None', 'visible': False}, 'type': 'dropdown'}, {'id': 15, 'props': {'style': {}, 'type': 'form', 'visible': True}, 'type': 'form'}, ...], 'css': '.output-html p {margin: 0 0.5em;}\n\n.row > *,\n.ro...ortant; }\n.meta-text { display:none!important; }\n', 'dependencies': [{'api_name': None, 'backend_fn': True, 'inputs': [], 'js': None, 'outputs': [], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [25], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [], 'js': None, 'outputs': [], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [26], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [], 'js': None, 'outputs': [35, 36, 36, 37], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [38], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [], 'js': None, 'outputs': [35, 36, 36, 37], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [39], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [], 'js': None, 'outputs': [65], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [66], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [], 'js': None, 'outputs': [75], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [76], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [70], 'js': None, 'outputs': [72, 81], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [70], 'trigger': 'change'}, {'api_name': None, 'backend_fn': True, 'inputs': [88], 'js': None, 'outputs': [89, 90], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [88], 'trigger': 'change'}, {'api_name': None, 'backend_fn': True, 'inputs': [86], 'js': None, 'outputs': [86, 87, 88, 89, 90, 92, 93, 96, 97, 99, 100], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [86], 'trigger': 'change'}, {'api_name': None, 'backend_fn': True, 'inputs': [124, 31], 'js': '(x, y) => [x, selected_gallery_index()]', 'outputs': [65, 31], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [67], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [124, 31], 'js': '(x, y) => [x, selected_gallery_index()]', 'outputs': [75, 31], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [77], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [6, 18, 14, 21, 42, 43, 49, 50, 58, 59, 61, 65, 75, 79, 83, 82, 70, 46, 45, 51, ...], 'js': 'submit', 'outputs': [109, 124, 123], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [6], 'trigger': 'submit'}, {'api_name': None, 'backend_fn': True, 'inputs': [6, 18, 14, 21, 42, 43, 49, 50, 58, 59, 61, 65, 75, 79, 83, 82, 70, 46, 45, 51, ...], 'js': 'submit', 'outputs': [109, 124, 123], 'queue': None, 'scroll_to_output': False, 'show_progress': False, 'targets': [27], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [51], 'js': None, 'outputs': [53], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [51], 'trigger': 'change'}, {'api_name': None, 'backend_fn': True, 'inputs': [124, 109, 118, 123], 'js': '(x, y, z, w) => [x, y, z, selected_gallery_index()]', 'outputs': [121, 123, 123, 123], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [112], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [6], 'js': 'update_txt2img_tokens', 'outputs': [6], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [9], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [6], 'js': None, 'outputs': [6, 18, 42, 43, 49, 61, 65, 45, 46, 59, 75, 79, 82, 83, 55, 51, 53], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [10], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [6, 42], 'js': None, 'outputs': [11], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [12], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [], 'js': None, 'outputs': [], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [151], 'trigger': 'click'}, {'api_name': None, 'backend_fn': True, 'inputs': [], 'js': None, 'outputs': [], 'queue': None, 'scroll_to_output': False, 'show_progress': True, 'targets': [152], 'trigger': 'click'}, ...], 'dev_mode': False, 'enable_queue': False, 'is_space': False, 'layout': {'children': [{'children': [{'children': [...], 'id': 527}], 'id': 525}, {'children': [{'children': [...], 'id': 529}, {'children': [...], 'id': 530}, {'children': [...], 'id': 531}, {'children': [...], 'id': 532}, {'children': [...], 'id': 533}, {'children': [...], 'id': 534}, {'children': [...], 'id': 535}], 'id': 528}, {'children': [{'id': 536}], 'id': 537}], 'id': 524}, 'mode': 'blocks', 'show_api': True, 'show_error': False, ...}
```

**Comment by zznewclear13** [comment]
Pretty strange, I tried on another PC, switched from original `webui` to `auto-sd-krita`, and it ran perfectly.

**Comment by zznewclear13** [comment]
Turned out I had another krita stable diffusion plugin, which caused this error.
