### ISSUE TITLE
ValueError:remove:path too long for windows

### ISSUE THREAD

**Issue by PTFish8** [Interpause/auto-sd-krita#29]
Before returning to the picture, a pop-up window will pop up, displaying "ValueError:remove:path too long for windows"

this is screenshot: ![image](https://user-images.githubusercontent.com/72650071/197260037-3ab1c64c-c69d-42bc-bcf4-5b1b8ad9894e.png)

this is content:I I I
                       VVV
                       v v v
ValueError
Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
Sat Oct 22 01:58:26 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py in cb()
  262             self.update_selection()
  263             self.adjust_selection()
  264             self.apply_img2img(mode=0)
  265             self.create_mask_layer_workaround()
  266             self.set_status(STATE_IMG2IMG)
self = <krita_diff.script.Script object>
self.apply_img2img = <bound method Script.apply_img2img of <krita_diff.script.Script object>>
mode undefined

 C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py in apply_img2img(self=<krita_diff.script.Script object>, mode=0)
  207             self.clear_temp_images([path, mask_path, *outputs])
  208         else:
  209             self.clear_temp_images([path, *outputs])
  210         self.doc.refreshProjection()
  211 
self = <krita_diff.script.Script object>
self.clear_temp_images = <bound method Script.clear_temp_images of <krita_diff.script.Script object>>
path = r'C:\Program My\auto-sd-krita-master\outputs\krita-in\1666375063.png'
outputs = ['iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...8coV2lq0VldYMOmxGpP8BjYm9tFzoCuEAAAAASUVORK5CYII=', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...Uq6WA/FRkcsYXtW+qxPr/ASpoKUQ+HAkpAAAAAElFTkSuQmCC', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA.../fiYHdKa58TjVqQEi4v8D32/37N9qQF4AAAAASUVORK5CYII=', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...N3eLLQ0YCb//t/FmEiPw/qUbRpmAjbLMAAAAASUVORK5CYII=']

 C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py in clear_temp_images(self=<krita_diff.script.Script object>, files=[r'C:\Program My\auto-sd-krita-master\outputs\krita-in\1666375063.png', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...8coV2lq0VldYMOmxGpP8BjYm9tFzoCuEAAAAASUVORK5CYII=', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...Uq6WA/FRkcsYXtW+qxPr/ASpoKUQ+HAkpAAAAAElFTkSuQmCC', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA.../fiYHdKa58TjVqQEi4v8D32/37N9qQF4AAAAASUVORK5CYII=', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...N3eLLQ0YCb//t/FmEiPw/qUbRpmAjbLMAAAAASUVORK5CYII='])
  239         if self.cfg("delete_temp_files", bool):
  240             for file in files:
  241                 os.remove(file)
  242 
  243     # Actions
global os = <module 'os' from 'C:\\Program Files\\Krita (x64)\\python\\python38.zip\\os.pyc'>
os.remove = <built-in function remove>
file = 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...8coV2lq0VldYMOmxGpP8BjYm9tFzoCuEAAAAASUVORK5CYII='
ValueError: remove: path too long for Windows
    __cause__ = None
    __class__ = <class 'ValueError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of ValueError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ValueError object>
    __doc__ = 'Inappropriate argument value (of correct type).'
    __eq__ = <method-wrapper '__eq__' of ValueError object>
    __format__ = <built-in method __format__ of ValueError object>
    __ge__ = <method-wrapper '__ge__' of ValueError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ValueError object>
    __gt__ = <method-wrapper '__gt__' of ValueError object>
    __hash__ = <method-wrapper '__hash__' of ValueError object>
    __init__ = <method-wrapper '__init__' of ValueError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ValueError object>
    __lt__ = <method-wrapper '__lt__' of ValueError object>
    __ne__ = <method-wrapper '__ne__' of ValueError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ValueError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ValueError object>
    __repr__ = <method-wrapper '__repr__' of ValueError object>
    __setattr__ = <method-wrapper '__setattr__' of ValueError object>
    __setstate__ = <built-in method __setstate__ of ValueError object>
    __sizeof__ = <built-in method __sizeof__ of ValueError object>
    __str__ = <method-wrapper '__str__' of ValueError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('remove: path too long for Windows',)
    with_traceback = <built-in method with_traceback of ValueError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py", line 264, in cb
    self.apply_img2img(mode=0)
  File "C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py", line 209, in apply_img2img
    self.clear_temp_images([path, *outputs])
  File "C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py", line 241, in clear_temp_images
    os.remove(file)
ValueError: remove: path too long for Windows

**Comment by PTFish8** [comment]
> Before returning to the picture, a pop-up window will pop up, displaying "ValueError:remove:path too long for windows"
> 
> this is screenshot: ![image](https://user-images.githubusercontent.com/72650071/197260037-3ab1c64c-c69d-42bc-bcf4-5b1b8ad9894e.png)
> 
> this is content:
