### ISSUE TITLE
ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed'

### ISSUE THREAD

**Issue by danilw** [Interpause/auto-sd-krita#55]
**Describe the bug**
(in log path has stable-diffusion-webui because I rename auto-sd-krita to it, when it is auto-sd-krita this modification)

```
Installing requirements for Web UI
Launching Web UI and Krita server with arguments: --share --gradio-debug --gradio-auth tester:tester123
Traceback (most recent call last):
  File "launch.py", line 233, in <module>
    start_krita_server()
  File "launch.py", line 227, in start_krita_server
    import krita_server
  File "/content/stable-diffusion-webui/krita_server/__init__.py", line 9, in <module>
    from webui import shared, webui
  File "/content/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers, upscaler
  File "/content/stable-diffusion-webui/modules/sd_samplers.py", line 10, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/stable-diffusion-webui/modules/processing.py", line 14, in <module>
    import modules.sd_hijack
  File "/content/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images
  File "/content/stable-diffusion-webui/modules/shared.py", line 14, in <module>
    import modules.sd_models
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 13, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack, should_hijack_inpainting
  File "/content/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 6, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 19, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py)
```

**To Reproduce**
https://stackoverflow.com/questions/74289972/cannot-import-name-rank-zero-only-from-pytorch-lightning-utilities-distribute
> pytorch_lightning has recently released a new version which will throw this error (version 1.8.0.post1 released on November 2nd 2022).

**Additional context**
Happening only on this auto-sd-krita plugin, in AUTOMATIC1111/stable-diffusion-webui not hapening

**Comment by Interpause** [comment]
They probably already fixed it upstream. I am not planning to maintain this version anymore though.

**Comment by danilw** [comment]
they fixed it by https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements.txt#L15
`pytorch_lightning==1.7.7`

but ye better archive this project then, and redirect everyone to new one

**Comment by danilw** [comment]
feel free to close this, I do not want do it without your response

**Comment by danilw** [comment]
This fixed (currently everything works), can be closed.
